// Code generated by protoc-gen-gogo.
// source: bolt.proto
// DO NOT EDIT!

/*
Package bolt is a generated protocol buffer package.

It is generated from these files:
	bolt.proto

It has these top-level messages:
	Job
	Playlist
	Track
	User
*/
package bolt

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	ID         int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerID    int64  `protobuf:"varint,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Type       string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	PlaylistID int64  `protobuf:"varint,5,opt,name=PlaylistID,proto3" json:"PlaylistID,omitempty"`
	URL        string `protobuf:"bytes,6,opt,name=URL,proto3" json:"URL,omitempty"`
	Error      string `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
	CreatedAt  int64  `protobuf:"varint,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptorBolt, []int{0} }

type Playlist struct {
	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *Playlist) Reset()                    { *m = Playlist{} }
func (m *Playlist) String() string            { return proto.CompactTextString(m) }
func (*Playlist) ProtoMessage()               {}
func (*Playlist) Descriptor() ([]byte, []int) { return fileDescriptorBolt, []int{1} }

type Track struct {
	ID         int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlaylistID int64  `protobuf:"varint,2,opt,name=PlaylistID,proto3" json:"PlaylistID,omitempty"`
	FileID     string `protobuf:"bytes,3,opt,name=FileID,proto3" json:"FileID,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	CreatedAt  int64  `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *Track) Reset()                    { *m = Track{} }
func (m *Track) String() string            { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()               {}
func (*Track) Descriptor() ([]byte, []int) { return fileDescriptorBolt, []int{2} }

type User struct {
	ID           int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MobileNumber string `protobuf:"bytes,2,opt,name=MobileNumber,proto3" json:"MobileNumber,omitempty"`
	CreatedAt    int64  `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt    int64  `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorBolt, []int{3} }

func init() {
	proto.RegisterType((*Job)(nil), "bolt.Job")
	proto.RegisterType((*Playlist)(nil), "bolt.Playlist")
	proto.RegisterType((*Track)(nil), "bolt.Track")
	proto.RegisterType((*User)(nil), "bolt.User")
}

func init() { proto.RegisterFile("bolt.proto", fileDescriptorBolt) }

var fileDescriptorBolt = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x25, 0xc9, 0x24, 0x6d, 0x2e, 0x8f, 0x87, 0x5c, 0xa4, 0xcc, 0x42, 0xa4, 0x64, 0xd5, 0x95,
	0x1b, 0xbf, 0x40, 0x8c, 0x42, 0x44, 0xab, 0xc4, 0xe4, 0x03, 0x32, 0x76, 0x16, 0xd1, 0xa9, 0x13,
	0x26, 0x53, 0xa5, 0x9f, 0xe3, 0x97, 0xf9, 0x2b, 0x92, 0x9b, 0xa9, 0x9a, 0x06, 0xba, 0x71, 0x77,
	0xce, 0xb9, 0xcc, 0x3d, 0xe7, 0x1e, 0x06, 0x40, 0x68, 0x65, 0xcf, 0x1a, 0xa3, 0xad, 0x46, 0xd6,
	0xe1, 0xe4, 0xd3, 0x83, 0xe0, 0x46, 0x0b, 0xfc, 0x0f, 0x7e, 0x96, 0x72, 0x6f, 0xee, 0x2d, 0x82,
	0xdc, 0xcf, 0x52, 0xe4, 0x30, 0xb9, 0x7f, 0x7f, 0x95, 0x26, 0x4b, 0xb9, 0x4f, 0xe2, 0x8e, 0x22,
	0x02, 0x2b, 0xb6, 0x8d, 0xe4, 0xc1, 0xdc, 0x5b, 0xc4, 0x39, 0x61, 0x9c, 0x41, 0xf4, 0x68, 0x2b,
	0xbb, 0x69, 0x39, 0x23, 0xd5, 0x31, 0x3c, 0x05, 0x78, 0x50, 0xd5, 0x56, 0xd5, 0xad, 0xcd, 0x52,
	0x1e, 0xd2, 0xa2, 0x5f, 0x0a, 0x1e, 0x41, 0x50, 0xe6, 0xb7, 0x3c, 0xa2, 0x47, 0x1d, 0xc4, 0x63,
	0x08, 0xaf, 0x8c, 0xd1, 0x86, 0x4f, 0x48, 0xeb, 0x09, 0x9e, 0x40, 0x7c, 0x69, 0x64, 0x65, 0xe5,
	0xea, 0xc2, 0xf2, 0x29, 0xad, 0xf9, 0x11, 0xba, 0x69, 0xd9, 0xac, 0xdc, 0x34, 0xee, 0xa7, 0xdf,
	0x42, 0xf2, 0x0c, 0xd3, 0x9d, 0xe3, 0xe8, 0x4a, 0x04, 0xb6, 0xac, 0xd6, 0x92, 0x4e, 0x8c, 0x73,
	0xc2, 0x43, 0xaf, 0xe0, 0xa0, 0x17, 0xdb, 0xf7, 0xfa, 0xf0, 0x20, 0x2c, 0x4c, 0xf5, 0xf4, 0x32,
	0x72, 0x1a, 0x36, 0xe1, 0x8f, 0x9a, 0x98, 0x41, 0x74, 0x5d, 0x2b, 0x99, 0xa5, 0xae, 0x57, 0xc7,
	0xba, 0x3e, 0x8a, 0xda, 0x2a, 0xe9, 0x8a, 0xed, 0xc9, 0x30, 0x63, 0x78, 0x30, 0x63, 0xb4, 0x9f,
	0xf1, 0x0d, 0x58, 0xd9, 0x4a, 0x33, 0x4a, 0x98, 0xc0, 0xbf, 0x3b, 0x2d, 0x6a, 0x25, 0x97, 0x9b,
	0xb5, 0x90, 0xc6, 0x75, 0x32, 0xd0, 0xfe, 0xd2, 0x8d, 0x88, 0xe8, 0xdb, 0x9d, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xef, 0x67, 0xc5, 0x6c, 0x84, 0x02, 0x00, 0x00,
}
